services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.38.0
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["tail", "-f", "/dev/null"] # Keeps the container running for manual commands.
